export const CORRECT_ANSWER_TIMEOUT = 1_000;
export const WRONG_ANSWER_TIMEOUT = 2_000;

export const SHOW_CATEGORY_VOTING_WINNER_TIMEOUT = 3_000;

export const SHOW_STARS_TIMEOUT = 5_000; 

export const SHOW_ANSWERS_TIMEOUT = 4_000; 